# 是否自动同意加好友 1-同意 0-不处理
autoFriend: 1
# 是否自动退群人数，当被好友拉进群时，群人数小于配置值自动退出， 默认50，0则不处理
autoQuit: 50
# 主人帐号
masterQQ:
  - "tg_5295641685"
  - "dc_1183068341968060438"
  - "2854201396:61C83695C859164A98267FAC62E60486"
  - 2785889402
# Bot账号:主人帐号
master:
  - "tg_6364307796:tg_5295641685"
  - "dc_1269584238689390612:dc_1183068341968060438"
  - "2854201396:2854201396:61C83695C859164A98267FAC62E60486"
  - 391601983:2785889402

# 禁用私聊功能 true：私聊只接受ck以及抽卡链接（Bot主人不受限制），false：私聊可以触发全部指令，默认false
disablePrivate: false
# 禁用私聊Bot提示内容
disableMsg: "私聊功能已禁用，仅支持发送cookie，抽卡记录链接，记录日志文件"
# 私聊通行字符串
disableAdopt:
  - stoken

#白名单群
whiteGroup:
#白名单用户
whiteUser:
#黑名单群
blackGroup:
  - 213938015
#黑名单用户
blackUser:
  - 528952540
  - 554593924
  - 3791368285
  - 1296371529
  - 960945944